/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EmployeList;
import model.Member;
import model.MemberList;

/**
 *
 * @author HAMIDREZA
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    private MemberList ml;
    private EmployeList el;

    public Search(MemberList ml, EmployeList el) {
        initComponents();
        this.ml = ml;
        this.el = el;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtxtEmployee = new javax.swing.JTextField();
        jcbEmployee = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEmployee = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlblResultE = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtxtMember = new javax.swing.JTextField();
        jcbMember = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblMember = new javax.swing.JTable();
        jbtnSearch = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jlblResultM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Employee/Member");

        jcbEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Name", "Last Name", "Telephone" }));

        jtblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Birth Date", "Telephone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblEmployee);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Result: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlblResultE, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jcbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlblResultE, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Employees", jPanel1);

        jtxtMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMemberActionPerformed(evt);
            }
        });

        jcbMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Name", "Last Name", "Telephone" }));

        jLabel2.setText("Result: ");

        jtblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Birth Date", "Telephone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtblMember);

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jlblResultM, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSearch)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnCancel))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jtxtMember, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jcbMember, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGap(19, 19, 19)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jlblResultM)
                .addContainerGap(354, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnSearch)
                        .addComponent(jbtnCancel))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Search Members", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object[] rowData = new Object[5];
        String search = jtxtEmployee.getText().toUpperCase();
        Object select = jcbEmployee.getSelectedItem();
        int result = 0;

        DefaultTableModel model = (DefaultTableModel) jtblEmployee.getModel();
        model.setRowCount(0);

        if (jtxtEmployee.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You need to fill something to search!", "Search Employee", JOptionPane.ERROR_MESSAGE);
        } else {
            //check if checkbox is equal to First Name
            if (select.equals("First Name")) {
                for (String s : el.keySet()) {
                    if (el.get(s).getFistName().toUpperCase().equals(search)) {
                        rowData[0] = el.get(s).getFistName();
                        rowData[1] = el.get(s).getLastName();
                        rowData[2] = el.get(s).getBirthdate();
                        rowData[3] = el.get(s).getTelephone();
                        rowData[4] = el.get(s).getEmail();
                        model.addRow(rowData);
                        result += 1;
                    }
                }
                jlblResultE.setText(result + " result(s) found");
            }
            //search if checkbox equal to Last Name
            if (select.equals("Last Name")) {
                for (String s : el.keySet()) {
                    if (el.get(s).getLastName().toUpperCase().equals(search)) {
                        rowData[0] = el.get(s).getFistName();
                        rowData[1] = el.get(s).getLastName();
                        rowData[2] = el.get(s).getBirthdate();
                        rowData[3] = el.get(s).getTelephone();
                        rowData[4] = el.get(s).getEmail();
                        model.addRow(rowData);
                        result += 1;
                    }
                }
                jlblResultE.setText(result + " result(s) found");
            }
            //search if checkbox equal to Telephone
            if (select.equals("Telephone")) {
                for (String s : el.keySet()) {
                    if (el.get(s).getTelephone().toUpperCase().equals(search)) {
                        rowData[0] = el.get(s).getFistName();
                        rowData[1] = el.get(s).getLastName();
                        rowData[2] = el.get(s).getBirthdate();
                        rowData[3] = el.get(s).getTelephone();
                        rowData[4] = el.get(s).getEmail();
                        model.addRow(rowData);
                        result += 1;
                    }
                }
                jlblResultE.setText(result + " result(s) found");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        Object[] rowData = new Object[5];
        String search = jtxtMember.getText().toUpperCase();
        Object select = jcbMember.getSelectedItem();
        int result = 0;

        DefaultTableModel model = (DefaultTableModel) jtblMember.getModel();
        model.setRowCount(0);

        if (jtxtMember.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You need to fill something to search!", "Search Employee", JOptionPane.ERROR_MESSAGE);
        } else {
            //check if checkbox is equal to First Name
            if (select.equals("First Name")) {
                for (int i = 0; i<ml.size(); i++) {
                    if (ml.get(i).getFistName().toUpperCase().equals(search)) {
                        rowData[0] = ml.get(i).getFistName();
                        rowData[1] = ml.get(i).getLastName();
                        rowData[2] = ml.get(i).getBirthdate();
                        rowData[3] = ml.get(i).getTelephone();
                        rowData[4] = ml.get(i).getEmail();
                        model.addRow(rowData);
                        result += 1;
                    }
                }
                jlblResultM.setText(result + " result(s) found");
            }
            //search if checkbox equal to Last Name
            if (select.equals("Last Name")) {
                for (int i = 0; i<ml.size(); i++) {
                    if (ml.get(i).getLastName().toUpperCase().equals(search)) {
                        rowData[0] = ml.get(i).getFistName();
                        rowData[1] = ml.get(i).getLastName();
                        rowData[2] = ml.get(i).getBirthdate();
                        rowData[3] = ml.get(i).getTelephone();
                        rowData[4] = ml.get(i).getEmail();
                        model.addRow(rowData);
                        result += 1;
                    }
                }
                jlblResultM.setText(result + " result(s) found");
            }
            //search if checkbox equal to Telephone
            if (select.equals("Telephone")) {
                for (int i = 0; i<ml.size(); i++) {
                    if (ml.get(i).getTelephone().toUpperCase().equals(search)) {
                        rowData[0] = ml.get(i).getFistName();
                        rowData[1] = ml.get(i).getLastName();
                        rowData[2] = ml.get(i).getBirthdate();
                        rowData[3] = ml.get(i).getTelephone();
                        rowData[4] = ml.get(i).getEmail();
                        model.addRow(rowData);
                        result += 1;
                    }
                }
                jlblResultM.setText(result + " result(s) found");
            }
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jtxtMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMemberActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Search().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JComboBox<String> jcbEmployee;
    private javax.swing.JComboBox<String> jcbMember;
    private javax.swing.JLabel jlblResultE;
    private javax.swing.JLabel jlblResultM;
    private javax.swing.JTable jtblEmployee;
    private javax.swing.JTable jtblMember;
    private javax.swing.JTextField jtxtEmployee;
    private javax.swing.JTextField jtxtMember;
    // End of variables declaration//GEN-END:variables
}
